# Generated by Django 2.2.15 on 2020-10-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_jsondata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsondata',
            name='user',
        ),
    ]
